# -*- coding: utf-8 -*-
"""Copia de Practico_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10G6Ft8qFXLYJPXWEYGkadNRlDm9_81ty

# Práctico: Estructuración de proyectos en Python + GitHub

### Objetivos:
- Estructurar correctamente un proyecto Python.
- Usar funciones con estructuras de control como `for` e `if`.
- Ejecutar funciones desde un notebook en Google Colab.
- Manejar repositorios con GitHub.

### Parte 1 – Estructura del proyecto

Estructurar el proyecto así:

```
mi_proyecto/
│
├── README.md
├── requirements.txt
├── main.py
├── .gitignore
├── src/
│   ├── __init__.py
│   └── operaciones.py
└── notebooks/
    └── uso_funciones.ipynb
```
"""

import os

os.makedirs("mi_proyecto", exist_ok=True)
os.makedirs("mi_proyecto/src", exist_ok=True)
os.makedirs("mi_proyecto/notebooks", exist_ok=True)

with open("mi_proyecto/README.md", "w") as f:
        f.write("# Mi Proyecto")

with open("mi_proyecto/requirements.txt", "w") as f:
        f.write("numpy")
        f.write("pandas")
        f.write("matplotlib")
        f.write("seaborn")
        f.write("scikit-learn")
        f.write("jupyterlab")
        f.write("google-colab")
        f.write("gitpython")
        f.write("pytest")
        f.write("flake8")
        f.write("black")
        f.write("mypy")
        f.write("pylint")
        f.write("pydocstyle")

with open("mi_proyecto/src/__init__.py", "w") as f:
        pass
    with open("mi_proyecto/src/operaciones.py", "w") as f:
        f.write("def filtrar_pares(lista):\n")
        f.write("    pares = []\n")
        f.write("    for numero in lista:\n")
        f.write("        if numero % 2 == 0:\n")
        f.write("            pares.append(numero)\n")
        f.write("    return pares\n")

with open("mi_proyecto/notebooks/uso_funciones.ipynb", "w") as f:
        f.write("# Uso de funciones\n")
        f.write("import numpy as np\n")
        f.write("import pandas as pd\n")
        f.write("import matplotlib.pyplot as plt\n")
        f.write("import seaborn as sns\n")
        f.write("from src.operaciones import filtrar_pares\n")
        f.write("\n")
        f.write("lista = np.random.randint(0, 100, 10)\n")
        f.write("print(lista)\n")
        f.write("\n")
        f.write("pares = filtrar_pares(lista)\n")
        f.write("print(pares)\n")

"""### Parte 2 – Función a desarrollar

En `src/operaciones.py`, crear una función `filtrar_pares(lista)` que reciba una lista de números y devuelva solo los números pares.

Usar un bucle `for` y una estructura `if` para resolverlo.

```python
def filtrar_pares(lista):
    # tu código acá
```

En `main.py`, probar la función con una lista de ejemplo.

En el notebook, importar y usar la función con otra lista.

"""

def filtrar_pares(lista):
    pares = []
    for numero in lista:
        if numero % 2 == 0:
            pares.append(numero)
    return pares

lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    pares = filtrar_pares(lista)
    print(pares)

"""### Parte 3 – GitHub + Colab

- Inicializar un repositorio con `git init`.
- Crear `.gitignore` para evitar subir archivos no deseados.
- Subir el proyecto a GitHub.
- Desde Google Colab:
  - Clonar el repositorio.
  - Ejecutar el notebook desde la carpeta clonada.
  - Hacer cambios y subirlos con `git add`, `commit`, `push`.

"""



"""### Entregable

- Link del repositorio GitHub.
- El notebook funcional.
- Código comentado en `operaciones.py`.
- `README.md` explicando cómo probar el proyecto.

"""